package janelaControleProjeto;

import controlDashBoard.Pessoa;
import controlDashBoard.Project;
import controlDashBoard.ProjectListModel;
import janelaDetalhesProjeto.JanelaDetalhesProjeto;
import JanelaPessoas.JanelaPessoas;
import controlDashBoard.Task;
import controleFuncionamento.SampleDataFuncionamento;
import janelaTarefa.JanelaAdicionarTarefa;
import janelaTarefa.JanelaVerTarefa;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Dashboard extends javax.swing.JFrame {

    public SampleDataFuncionamento sp;
    private JanelaDetalhesProjeto jdp;
    private JanelaAdicionarTarefa jat;
    private JanelaPessoas jp;
    private JanelaVerTarefa jvt;
    
    public Dashboard(JanelaDetalhesProjeto jdp, 
            JanelaAdicionarTarefa jat, JanelaPessoas jp,
            JanelaVerTarefa jvt, SampleDataFuncionamento sp) {
        super("DashBoard");
        initComponents();
        this.sp = sp;
        this.jdp = jdp;
        this.jat = jat;
        this.jp = jp;
        this.jvt = jvt;
        listaProjetos.setModel(new ProjectListModel(sp.getProjeto()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlProjetos = new javax.swing.JLabel();
        txtProjectTitulo = new javax.swing.JTextField();
        btNewProject = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProjetos = new javax.swing.JList<>();
        btDetailsProject = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtProjectDescrition = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnGerenciarPessoa = new javax.swing.JButton();
        excluirProjeto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlProjetos.setText("Projeto:");

        txtProjectTitulo.setText("Digite aqui o nome do novo projeto...");
        txtProjectTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectTituloActionPerformed(evt);
            }
        });

        btNewProject.setText("Criar Projeto");
        btNewProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewProjectActionPerformed(evt);
            }
        });

        listaProjetos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaProjetos.setToolTipText("");
        jScrollPane1.setViewportView(listaProjetos);

        btDetailsProject.setText("Ver detalhes");
        btDetailsProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDetailsProjectActionPerformed(evt);
            }
        });

        jLabel2.setText("Descrição:");

        txtProjectDescrition.setColumns(20);
        txtProjectDescrition.setRows(5);
        jScrollPane2.setViewportView(txtProjectDescrition);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setText("Projetos Existentes");

        btnGerenciarPessoa.setText("Gerenciar Pessoas");
        btnGerenciarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarPessoaActionPerformed(evt);
            }
        });

        excluirProjeto.setText("Excluir Projeto");
        excluirProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirProjetoActionPerformed(evt);
            }
        });

        jLabel1.setText("Adicione, altere e exclua pessoas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProjectTitulo)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btNewProject)))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btDetailsProject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(excluirProjeto))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnGerenciarPessoa))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlProjetos)
                    .addComponent(txtProjectTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 48, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(btNewProject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDetailsProject)
                    .addComponent(excluirProjeto))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerenciarPessoa)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProjectTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectTituloActionPerformed

    }//GEN-LAST:event_txtProjectTituloActionPerformed

    private void btNewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewProjectActionPerformed

        Project projeto;
        try {
            if (txtProjectTitulo.getText() == null || txtProjectTitulo.getText().equals("Digite aqui o nome do novo projeto...")) {
                JOptionPane.showMessageDialog(null, "Você deveria ter digitado um nome correto.", "Digite um nome correto", JOptionPane.INFORMATION_MESSAGE);
            } else {
                projeto = new Project(txtProjectTitulo.getText(), txtProjectDescrition.getText());
                sp.getDaoProjeto().criar(projeto);
                sp.getProjeto().add(projeto);
                listaProjetos.updateUI();
            }
        } catch (Exception ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btNewProjectActionPerformed

    private void btDetailsProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDetailsProjectActionPerformed
        Project selecionado = listaProjetos.getSelectedValue();
        if (selecionado == null) {
            JOptionPane.showMessageDialog(null, "Você deveria ter selecionado um projeto.", "Selecione um projeto.", JOptionPane.INFORMATION_MESSAGE);

        } else {
            try {
            jdp = new JanelaDetalhesProjeto(selecionado, jat, jvt, sp);
            jdp.setVisible(true);
            jdp.setLocationRelativeTo(null);
            jdp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            } catch (Exception ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btDetailsProjectActionPerformed

    private void btnGerenciarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarPessoaActionPerformed
        jp = new JanelaPessoas(sp.getPessoa(), sp);
        jp.setSize(410,300);
        jp.setLocationRelativeTo(null);
        jp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jp.setVisible(true);
    }//GEN-LAST:event_btnGerenciarPessoaActionPerformed

    private void excluirProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirProjetoActionPerformed
        Project selecionado = listaProjetos.getSelectedValue();
        if (selecionado == null) {
            JOptionPane.showMessageDialog(null, "Você deveria ter selecionado um projeto.", "Selecione um projeto.", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                if (selecionado.getTarefas().size() > 0)
                {
                    for (Task tar: sp.getDaoTask().listarTodos(selecionado.getId()))
                    {
                        System.out.println("q");
                        sp.getDaoTaskPessoa().buscar(tar, sp.getPessoa());
                        if (sp.getDaoTask().listarTodos(selecionado.getId()).size() > 1)
                        {
                            sp.getDaoTaskPreRequisito().excluir(tar.getNumero_tarefa());
                            for (Pessoa pes: tar.getPessoa())
                            {
                                sp.getDaoTaskPessoa().excluir(tar.getNumero_tarefa());
                            }
                        }
                        else
                        {
                            sp.getDaoTaskPreRequisito().excluir(tar.getNumero_tarefa());
                            sp.getDaoTaskPessoa().excluir(tar.getNumero_tarefa());
                        }
                    }
                    for (Task t : selecionado.getTarefas())
                    {
                        sp.getDaoTask().excluir(t);
                    }
                    sp.getDaoProjeto().excluir(selecionado);
                    sp.getProjeto().remove(listaProjetos.getSelectedValue());
                    listaProjetos.updateUI();
                }
                else
                {
                    sp.getDaoProjeto().excluir(selecionado);
                    sp.getProjeto().remove(listaProjetos.getSelectedValue());
                    listaProjetos.updateUI();
                }
            } catch (Exception ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_excluirProjetoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDetailsProject;
    private javax.swing.JButton btNewProject;
    private javax.swing.JButton btnGerenciarPessoa;
    private javax.swing.JButton excluirProjeto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlProjetos;
    private javax.swing.JList<Project> listaProjetos;
    private javax.swing.JTextArea txtProjectDescrition;
    private javax.swing.JTextField txtProjectTitulo;
    // End of variables declaration//GEN-END:variables
}
